'use strict';
// The DOM below is a deterministic interaction harness, not a browser or layout audit.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const UI=require('../src/pwb/assets/app.js');
const field=(name,value,type='text',dataType='string')=>({name,value,type,checked:false,dataset:{type:dataType},required:false});
function makeForm(mode,values={}){
 const elements=Object.entries(values).map(([name,value])=>field(name,value));
 for(const el of elements)elements[el.name]=el;
 const error={hidden:true,textContent:'',scrollIntoView(){}};
 return {dataset:{mode,runId:'parent-run',candidateId:'candidate-0'},elements,error,querySelector(){return error;},classList:{add(){},remove(){}}};
}
async function main(){
 const requests=[],timers=[],nodes={},loadedScripts=[],viewers=[];let domReplacements=0,polledRun={id:'parent-run',name:'Test export',config:{},status:'DRAFT',workflow:'bindcraft'};
 const createViewer=element=>{const viewer={element,styles:[],cleared:false,clear(){this.cleared=true;},setStyle(selection,style){this.styles.push({selection,style});},addModel(text,format){this.format=format;return {selectedAtoms(){return [{chain:'A',resi:1},{chain:'B',resi:2}];}};},zoomTo(){},render(){}};viewers.push(viewer);return viewer;};
 const node=()=>({innerHTML:'',textContent:'',hidden:true,dataset:{},listeners:{},addEventListener(name,fn){this.listeners[name]=fn;},focus(){},contains(){return false;},querySelector(){return null;},querySelectorAll(){return [];},replaceChildren(){this.innerHTML='';}});
 const app=node(),dialog=node();let appHTML='';Object.defineProperty(app,'innerHTML',{get(){return appHTML;},set(value){appHTML=value;if(value.includes('id="molecular-comparison"')){const placeholder=node();placeholder.replaceWith=retained=>{nodes['molecular-comparison']=retained;domReplacements++;};nodes['molecular-comparison']=placeholder;}}});dialog.showModal=()=>{dialog.open=true;};dialog.close=()=>{dialog.open=false;};dialog.querySelector=selector=>selector==='form'?dialog.form:selector==='#import-inspection'?nodes.inspection:null;
 for(const name of ['toast','announcer','main','molecular-comparison','molecule-0','molecule-1','molecule-status-0','molecule-status-1','molecule-controls-0','molecule-controls-1'])nodes[name]=node();nodes.inspection=node();
 const document={head:{appendChild(script){loadedScripts.push(script.src);window.$3Dmol={createViewer};script.onload();}},createElement(){return {remove(){}};},hidden:false,activeElement:null,querySelector(selector){if(selector==='#app')return app;if(selector==='#form-dialog')return dialog;if(selector==='meta[name="csrf-token"]')return {content:'TEST-CSRF'};return nodes[selector.slice(1)]||null;},querySelectorAll(){return [];},getElementById(id){return nodes[id]||null;},addEventListener(){}};
 const state={projects:[{id:'project-1',name:'Test project'}],environments:[{id:'env-1',name:'CPU test environment'}],templates:[{id:'bindcraft',title:'BindCraft',fields:[{name:'settings',type:'string'}]},{id:'gromacs_md',title:'MD',fields:[{name:'input_mode',type:'string',required:true},{name:'mdp',type:'json',required:true},{name:'analysis',type:'json',required:true}]},{id:'gromacs_pull_force',title:'Force pulling',fields:[{name:'pull',type:'json'}]}],runs:[],resources:[],queue:[],current:null};
 const window={scrollX:0,scrollY:0,scrollTo(){}};
 const context={window,document,console,Map,Set,Date,setTimeout(){return 1;},clearTimeout(){},setInterval(fn,ms){timers.push({fn,ms});},fetch:async(url,options={})=>{requests.push({url,options,body:options.body?JSON.parse(options.body):null});let data=url==='/api/state'?state:url==='/api/inspect'?{entries:['a.py','nested/b.ipynb'],files:4,sha256:'TEST-HASH'}:url==='/api/export'?{url:'/api/feedback/parent-run'}:url==='/api/run/parent-run'?JSON.parse(JSON.stringify(polledRun)):{};return {ok:true,status:200,json:async()=>data,text:async()=>'ATOM fake text parsed by the viewer stub'};}};
 let source=fs.readFileSync(path.join(__dirname,'../src/pwb/assets/app.js'),'utf8');
 // Expose lexical handlers inside this test sandbox; production globals remain unchanged.
 source=source.replace('  render();refresh();if(!demo)', '  root.TestUI={openForm,submitForm,mutate,runDetails,stages,evidence,showSelectedStructures,clearViewers,selectCandidates:ids=>{selectedCandidates.clear();for(const id of ids)selectedCandidates.add(id);},setDetail:r=>{detail=r;selectedRun=r.id;view="run";detailTab="candidates";}};render();refresh();if(!demo)');
 vm.runInNewContext(source,context);await new Promise(resolve=>setImmediate(resolve));
 const runtime=window.TestUI;
 assert.deepEqual(timers.map(x=>x.ms),[30000,15000]);
 runtime.openForm('child',{id:'parent-run',name:'Upstream',workflow:'bindcraft',project_id:'project-1',environment_id:'env-1',config:{settings:'/upstream-only',downstream:[{enabled:true}]}},'candidate-0');
 assert.match(dialog.innerHTML,/从所选候选创建 MD 草稿/);
 assert.match(dialog.innerHTML,/<option value="gromacs_md" selected>/);
 assert.doesNotMatch(dialog.innerHTML,/<option value="bindcraft"/);
 assert.doesNotMatch(dialog.innerHTML,/upstream-only/);
 assert.doesNotMatch(dialog.innerHTML,/name="name"/,'child API generates name from parent, without unsupported name argument');
 assert.match(dialog.innerHTML,/name="downstream_enabled" type="checkbox">/,'automatic scheduling always begins off');
 const savedDialog=dialog.innerHTML;timers[0].fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(dialog.innerHTML,savedDialog,'polling does not replace the open form or its input state');
 const md={production:{nsteps:200,dt:0.002}};
 const child=makeForm('child',{name:'MD follow-up',project_id:'project-1',environment_id:'env-1',workflow:'gromacs_md','cfg:input_mode':'protein_pdb','cfg:mdp':JSON.stringify(md),'cfg:analysis':JSON.stringify({energy_terms:['Potential']})});child.elements['cfg:mdp'].dataset.type='json';child.elements['cfg:analysis'].dataset.type='json';
 await runtime.submitForm(child);
 const post=requests.find(x=>x.url==='/api/child');
 assert.equal(post.options.headers['X-Workbench-Token'],'TEST-CSRF');
 assert.deepEqual(post.body,{project_id:'project-1',environment_id:'env-1',workflow:'gromacs_md',run_id:'parent-run',candidate_id:'candidate-0',config:{input_mode:'protein_pdb',mdp:md,analysis:{energy_terms:['Potential']}}});
 assert.equal(child.error.hidden,true);
 const builtIn=makeForm('create',{name:'MD initial',project_id:'project-1',environment_id:'env-1',workflow:'gromacs_md'});await runtime.submitForm(builtIn);assert.deepEqual(requests.find(x=>x.url==='/api/create').body,{name:'MD initial',project_id:'project-1',environment_id:'env-1',workflow:'gromacs_md',config:{}});
 const plan={enabled:true,rule:'ranking_score_desc',count:2,workflow:'gromacs_md',environment_id:'env-1',config:{mdp:md,analysis:{energy_terms:['Potential']}}};
 const automatic=makeForm('clone',{name:'Explicit clone',project_id:'project-1',environment_id:'env-1',extra_config:JSON.stringify({downstream:[plan],custom:true}),downstream_plans:JSON.stringify([plan]),downstream_enabled:''});automatic.elements.downstream_enabled.type='checkbox';
 assert.deepEqual(UI.formConfig(automatic),{downstream:[],custom:true},'extra JSON cannot bypass automatic opt-in');
 automatic.elements.downstream_enabled.checked=true;
 assert.deepEqual(UI.formConfig(automatic),{downstream:[plan],custom:true});
 await runtime.submitForm(automatic);
 const clone=requests.find(x=>x.url==='/api/clone');assert.deepEqual(clone.body.config.downstream,[plan]);assert.equal(clone.body.run_id,'parent-run');assert.equal(clone.body.environment_id,'env-1');assert.ok(!('project_id' in clone.body));
 automatic.elements.downstream_plans.value=JSON.stringify([{...plan,count:0}]);assert.throws(()=>UI.formConfig(automatic),/正整数/);
 automatic.elements.downstream_plans.value='[]';assert.throws(()=>UI.formConfig(automatic),/非空/);
 const importing=makeForm('import',{name:'Imported ZIP',project_id:'project-1',environment_id:'env-1',workflow:'generic_notebook',path:'/server/input.zip',entrypoint:'nested/b.ipynb'});
 await runtime.submitForm(importing);assert.match(importing.error.textContent,/先检查/);assert.equal(requests.filter(x=>x.url==='/api/import').length,0);
 dialog.form=importing;
 await dialog.listeners.click({preventDefault(){},target:{closest(selector){return selector==='[data-action="inspect"]'?{}:null;}}});
 assert.equal(importing.dataset.inspectedPath,'/server/input.zip');assert.match(nodes.inspection.innerHTML,/<option value="">请选择一个已检查入口<\/option>/);assert.match(nodes.inspection.innerHTML,/nested\/b.ipynb/);
 await runtime.submitForm(importing);const imported=requests.find(x=>x.url==='/api/import');assert.equal(imported.body.config.entrypoint,'nested/b.ipynb');
 importing.elements.path.value='/server/another.zip';dialog.listeners.input({target:{name:'path'}});assert.equal(importing.dataset.inspectedPath,undefined);
 assert.match(nodes.inspection.textContent,/重新检查/);
 runtime.setDetail({id:'parent-run',name:'Test export',config:{},status:'DRAFT',workflow:'bindcraft'});
 await runtime.mutate('export',{run_id:'parent-run'});assert.match(runtime.runDetails(),/href="\/api\/feedback\/parent-run" download/);
 const candidatesHTML=runtime.evidence({id:'parent-run',candidates:[{id:'valid',committed:true,structure:'models/candidate.pdb'},{id:'invalid',committed:true,valid_output:false,structure:'../unsafe.pdb'}]});assert.match(candidatesHTML,/href="\/api\/files\/parent-run\/models\/candidate.pdb" download/);assert.doesNotMatch(candidatesHTML,/href="[^"]*unsafe.pdb/);assert.match(candidatesHTML,/data-candidate-id="invalid" disabled/);
 assert.match(runtime.stages({progress:{stages:[{name:'production',status:'RUNNING',completed:0,actual:1,new:0,reused:0,invalid:0,live:{observed_step:250,configured_nsteps:1000,observed_time_ps:.5}}]}}),/已提交 0 \/ 1/);
 assert.match(runtime.stages({progress:{stages:[{name:'production',live:{observed_step:250,configured_nsteps:1000}}]}}),/绝对步数可能含 restart/);
 assert.equal(loadedScripts.length,0,'viewer library is not loaded by dashboard or form actions');
 polledRun={id:'parent-run',name:'Three candidates',config:{},status:'DRAFT',workflow:'sr56',candidates:[{id:'pdb',structure:'models/candidate.pdb',structure_sha256:'PDB-HASH',target_chains:['A'],binder_chains:['B'],metrics:{contact_residue_ids:[{chain:'B',resi:2}]}},{id:'cif',structure:'models/candidate.cif',structure_sha256:'CIF-HASH'},{id:'third',structure:'models/not-loaded.pdb'}]};runtime.setDetail(polledRun);runtime.selectCandidates(['pdb','cif','third']);
 await runtime.showSelectedStructures();assert.deepEqual(loadedScripts,['/assets/3Dmol-min.js']);assert.equal(viewers.length,2,'at most two viewer instances are created');assert.equal(viewers[0].format,'pdb');assert.equal(viewers[1].format,'cif');assert.ok(!requests.some(x=>x.url.includes('not-loaded')));
 assert.match(nodes['molecule-controls-0'].innerHTML,/data-view-chain="A"/);assert.match(nodes['molecule-controls-0'].innerHTML,/来源标注接触位点/);
 app.listeners.change({target:{dataset:{viewSlot:'0',viewChain:'B'},checked:false}});assert.equal(viewers[0].styles.at(-1).selection.chain,'B');assert.equal(Object.keys(viewers[0].styles.at(-1).style).length,0);
 const retainedBox=nodes['molecular-comparison'],firstViewer=viewers[0],secondViewer=viewers[1];firstViewer.rotation='USER-ROTATED';const stylesBeforePoll=firstViewer.styles.length;
 const focusedChain={dataset:{viewSlot:'0',viewChain:'B'},focus(){this.restored=true;}};document.activeElement=focusedChain;retainedBox.contains=element=>element===focusedChain;
 polledRun={...polledRun,name:'Updated progress while rotating'};timers[0].fn();await new Promise(resolve=>setImmediate(resolve));
 assert.equal(nodes['molecular-comparison'],retainedBox,'poll restores the original molecular DOM rather than rebuilding viewers');assert.equal(domReplacements,1);assert.equal(viewers.length,2);assert.equal(firstViewer.cleared,false);assert.equal(secondViewer.cleared,false);assert.equal(firstViewer.rotation,'USER-ROTATED');assert.equal(firstViewer.styles.length,stylesBeforePoll,'poll leaves hidden chain and model styles untouched');assert.equal(focusedChain.restored,true,'original viewer control focus is restored after DOM reattachment');document.activeElement=null;assert.match(app.innerHTML,/Updated progress while rotating/,'other run data still updates');
 polledRun={...polledRun,candidates:polledRun.candidates.map(c=>c.id==='pdb'?{...c,structure_sha256:'PDB-HASH-V2'}:c)};timers[0].fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(firstViewer.cleared,true,'changed structure SHA disposes prior context');assert.equal(secondViewer.cleared,true);assert.notEqual(nodes['molecular-comparison'],retainedBox);
 await runtime.showSelectedStructures();const pathChangedViewers=viewers.slice(-2);polledRun={...polledRun,candidates:polledRun.candidates.map(c=>c.id==='cif'?{...c,structure:'models/revised.cif'}:c)};timers[0].fn();await new Promise(resolve=>setImmediate(resolve));assert.ok(pathChangedViewers.every(v=>v.cleared),'changed structure path disposes prior contexts');
 await runtime.showSelectedStructures();const changedSelectionViewers=viewers.slice(-2);app.listeners.change({target:{dataset:{candidate:'third'},checked:false}});assert.ok(changedSelectionViewers.every(v=>v.cleared),'user candidate selection change disposes old combination');
 const fetchBeforePending=context.fetch;let releasePending,pendingFileSeen=false;context.fetch=async(url,options)=>{if(url.startsWith('/api/files/')&&!pendingFileSeen){pendingFileSeen=true;return new Promise(resolve=>{releasePending=()=>resolve({ok:true,status:200,text:async()=>'ATOM async during unchanged poll'});});}return fetchBeforePending(url,options);};
 const pendingShow=runtime.showSelectedStructures();await new Promise(resolve=>setImmediate(resolve));const pendingBox=nodes['molecular-comparison'];timers[0].fn();await new Promise(resolve=>setImmediate(resolve));assert.equal(nodes['molecular-comparison'],pendingBox,'unchanged polling preserves a loading structure DOM');releasePending();await pendingShow;assert.equal(viewers.filter(v=>!v.cleared).length,2,'unchanged polling retains generation so pending two-viewer load completes safely');context.fetch=fetchBeforePending;
 const stableCount=viewers.length;runtime.clearViewers();assert.ok(viewers.every(x=>x.cleared),'cleared render does not retain old viewer instances');
 let release;const originalFetch=context.fetch;context.fetch=async()=>new Promise(resolve=>{release=()=>resolve({ok:true,status:200,text:async()=>'ATOM fake delayed'});});const delayed=runtime.showSelectedStructures();await new Promise(resolve=>setImmediate(resolve));runtime.clearViewers();release();await delayed;assert.equal(viewers.length,stableCount,'stale async response after rerender cannot recreate a viewer');context.fetch=originalFetch;
 window.$3Dmol={createViewer(){throw new Error('TEST WebGL unavailable');}};await runtime.showSelectedStructures();assert.match(nodes['molecule-status-0'].textContent,/TEST WebGL unavailable/);assert.match(nodes['molecule-status-0'].textContent,/下载与指标仍可使用/);
 console.log('PASS: DOM-mock handlers submit exact child/clone/import POST bodies, require ZIP selection, preserve explicit opt-in, expose export link, separate live progress, load two local PDB/CIF viewers, preserve DOM/rotation/chain state on polling, invalidate on SHA/path/selection changes and recover from WebGL failure. No browser or scientific acceptance implied.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
