'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const UI=require('../src/pwb/assets/app.js');
assert.equal(UI.esc('<script>" &'), '&lt;script&gt;&quot; &amp;');
assert.equal(UI.safeURL('javascript:alert(1)'),null);
assert.equal(UI.safeURL('//external.test/a'),null);
assert.equal(UI.safeURL('/api/files/run-1/%2e%2e/secret'),null);
assert.equal(UI.safeURL('/\\external.test/a'),null);
assert.equal(UI.safeURL(' https://example.test/report'),null);
assert.equal(UI.safeURL('/api/files/run-1/../secret'),null);
assert.equal(UI.safeURL('/api/files/run-1/output/report.html'),'/api/files/run-1/output/report.html');
assert.equal(UI.safeURL('./demo-report.html'),'./demo-report.html');
assert.equal(UI.safeURL('https://example.test/report'),'https://example.test/report');
assert.deepEqual(UI.progress({actual:10,planned_upper:100,completed:6}),{done:6,denominator:10,percent:60,known:true});
assert.equal(UI.progress({actual:null,planned_upper:null,completed:6}).known,false);
assert.equal(UI.progress({actual:2,completed:4}).percent,100);
const structures={id:'r',candidates:[{id:'A',structure:'a.pdb',structure_sha256:'a'},{id:'B',structure:'b.cif',structure_sha256:'b'}]};
assert.equal(UI.structureViewIdentity(structures,['A','B']),UI.structureViewIdentity({...structures,candidates:structures.candidates.slice().reverse()},['A','B']));
assert.notEqual(UI.structureViewIdentity(structures,['A','B']),UI.structureViewIdentity({...structures,candidates:[{...structures.candidates[0],structure_sha256:'changed'},structures.candidates[1]]},['A','B']));
assert.notEqual(UI.structureViewIdentity(structures,['A','B']),UI.structureViewIdentity({...structures,id:'other-run'},['A','B']));
assert.equal(UI.resourceMetric([{gpu_utilization:0}],['gpu_utilization']),0);
assert.equal(UI.resourceMetric([{gpu_utilization:null}],['gpu_utilization']),null);
assert.equal(UI.resourceMetric([{gpu_utilization:10},{gpu_utilization:22}],['gpu_utilization']),22);
assert.equal(UI.resourceMetric([{gpu_utilization:10},{availability:'unavailable'}],['gpu_utilization']),null,'current missing sample must not appear as live previous data');
assert.equal(UI.normalizeResource({gpus:[{utilization_pct:70,memory_used_mb:2048}],memory:{MemTotal:4294967296,MemAvailable:1073741824},disk:{free:1073741824}}).gpu_memory_used_gb,2);
assert.equal(UI.normalizeResource({memory:{MemTotal:4294967296,MemAvailable:1073741824}}).ram_used_gb,3);
assert.match(UI.resourceDetails({cpu_load:[0,0,0],memory:{SwapTotal:0,SwapFree:0},gpus:[{memory_used_mb:12345,process_memory_mb:0}]}),/0 \/ 0 \/ 0/);
assert.match(UI.resourceDetails({cpu_load:[0,0,0],memory:{SwapTotal:0,SwapFree:0},gpus:[{memory_used_mb:12345,process_memory_mb:0}]}),/GPU 0：0 MB/);
assert.match(UI.resourceDetails({memory:{SwapTotal:1073741824,SwapFree:0}}),/1 \/ 1 GB/);
assert.match(UI.resourceDetails({gpus:[{memory_used_mb:12345}]}),/GPU 0：不可用/);
assert.doesNotMatch(UI.resourceDetails({gpus:[{memory_used_mb:12345}]}),/12345/);
assert.match(UI.resourceDetails({}),/不可用/);
assert.deepEqual(UI.candidateMetrics({id:'x',metrics:{ipTM:0,contacts:0}}),{ipTM:0,contacts:0});
assert.deepEqual(UI.candidateMetrics({id:'x',iptm:.8,notes:'not a metric'}),{iptm:.8});
assert.match(UI.sparkline([0,0,0]),/polyline/);
assert.match(UI.sparkline([null]),/历史样本不足/);
const mdLive=UI.liveProgress({live:{observed_step:0,configured_nsteps:200,observed_time_ps:0,source:'GROMACS md.log'}});
assert.match(mdLive,/尚未提交/);assert.match(mdLive,/绝对步数可能含 restart/);assert.doesNotMatch(mdLive,/0%/);
const bcLive=UI.liveProgress({live:{attempted_trajectories:8,recorded_trajectory_rows:5,mpnn_rows:3,accepted_files:0,accepted_goal:4,final_rows:0,max_trajectories:100,counts_are_separate_denominators:true}});
assert.match(bcLive,/Accepted PDB 文件/);assert.match(bcLive,/文件或 CSV 行不是已提交候选/);assert.doesNotMatch(bcLive,/8 \/ 4/);
assert.match(UI.liveProgress({live:{state:'<unknown>'}}),/&lt;unknown&gt;/);
const assets=path.join(__dirname,'../src/pwb/assets');
for(const mode of ['normal','empty','failed','rich']){
 const context={window:{},document:{documentElement:{dataset:{demo:mode}}}};
 vm.runInNewContext(fs.readFileSync(path.join(assets,'demo-fixtures.js'),'utf8'),context);
 const state=context.window.PWB_DEMO_STATE;
 assert.ok(state.templates.length>=3);
 if(mode==='empty')assert.equal(state.runs.length,0);
 if(mode==='rich')assert.ok(state.runs.length>6,'original six classifications must not limit history cards');
 if(mode==='failed'){assert.equal(state.paused,true);assert.equal(state.current,null);}
 assert.match(fs.readFileSync(path.join(assets,`demo-${mode}.html`),'utf8'),/demo-fixtures.js/);
}
const source=fs.readFileSync(path.join(assets,'app.js'),'utf8');
assert.match(source,/X-Workbench-Token/);
assert.match(source,/refresh\(\);},30000/);
assert.match(source,/refresh\(\{resourcesOnly:true\}\);},15000/);
assert.match(source,/const text=await response.text\(\)/);
assert.match(source,/safe_stop/);
const css=fs.readFileSync(path.join(assets,'app.css'),'utf8');
assert.match(css,/prefers-reduced-motion/);
for(const asset of [...css.matchAll(/url\('([^']+)'\)/g)].map(x=>x[1]))assert.ok(fs.existsSync(path.join(assets,asset)),`offline font exists: ${asset}`);
assert.doesNotMatch(css,/@import|url\(['"]?https?:/);
for(const mode of ['normal','empty','failed','rich'])assert.doesNotMatch(fs.readFileSync(path.join(assets,`demo-${mode}.html`),'utf8'),/(?:src|href)=['"]https?:/);
console.log('PASS: UI pure functions, evidence boundaries, fixtures, security and polling contract. Browser acceptance is a separate check.');
